apiVersion: v1
kind: Secret
metadata:
  name: clerk-secrets
  namespace: default
  labels:
    app: mealprep360
    tier: backend
    managed-by: kubectl
    environment: dev
    service: label-service
    component: auth
    owner: bcedergren
    created: "2025-10-10"
type: Opaque
stringData:
  CLERK_JWKS_URL: "https://clerk.example/.well-known/jwks.json"
  CLERK_JWT_ISSUER: "https://clerk.example"
  CLERK_JWT_AUDIENCE: "api.mealprep360"
