import { Recipe } from '../types/recipe';

export const DEFAULT_RECIPES: Recipe[] = [
	{
		id: 'default-dinner-1',
		userId: 'default-user',
		name: 'Baked Salmon',
		description: 'Oven-baked salmon with vegetables',
		ingredients: [
			{ name: 'salmon fillet', amount: 1, unit: 'piece' },
			{ name: 'broccoli', amount: 2, unit: 'cups' },
			{ name: 'sweet potato', amount: 1, unit: 'whole' },
			{ name: 'olive oil', amount: 2, unit: 'tbsp' },
			{ name: 'lemon', amount: 1, unit: 'whole' },
			{ name: 'garlic', amount: 2, unit: 'cloves' },
		],
		instructions: [
			'Preheat oven to 400°F',
			'Cut sweet potato into cubes',
			'Season salmon with garlic and lemon',
			'Place salmon and vegetables on baking sheet',
			'Drizzle with olive oil',
			'Bake for 20-25 minutes until salmon is cooked through',
		],
		prepTime: 15,
		cookTime: 25,
		servings: 1,
		nutritionalInfo: {
			calories: 550,
			protein: 40,
			carbs: 45,
			fat: 20,
		},
		tags: ['dinner'],
		dietaryPreferences: ['pescatarian'],
		restrictions: [],
	},
	{
		id: 'default-dinner-2',
		userId: 'default-user',
		name: 'Vegetable Stir Fry',
		description: 'Quick and healthy vegetable stir fry with tofu',
		ingredients: [
			{ name: 'tofu', amount: 1, unit: 'block' },
			{ name: 'mixed vegetables', amount: 3, unit: 'cups' },
			{ name: 'soy sauce', amount: 2, unit: 'tbsp' },
			{ name: 'sesame oil', amount: 1, unit: 'tbsp' },
			{ name: 'ginger', amount: 1, unit: 'tbsp' },
			{ name: 'brown rice', amount: 1, unit: 'cup' },
		],
		instructions: [
			'Press and cube tofu',
			'Cook brown rice according to package instructions',
			'Heat sesame oil in a large pan',
			'Stir fry vegetables until crisp-tender',
			'Add tofu and sauce',
			'Cook until heated through',
			'Serve over brown rice',
		],
		prepTime: 10,
		cookTime: 20,
		servings: 1,
		nutritionalInfo: {
			calories: 400,
			protein: 20,
			carbs: 35,
			fat: 15,
		},
		tags: ['dinner'],
		dietaryPreferences: ['vegetarian', 'vegan'],
		restrictions: [],
	},
	{
		id: 'default-dinner-3',
		userId: 'default-user',
		name: 'Chicken and Rice Bowl',
		description: 'Simple and satisfying chicken and rice bowl',
		ingredients: [
			{ name: 'chicken breast', amount: 1, unit: 'piece' },
			{ name: 'brown rice', amount: 1, unit: 'cup' },
			{ name: 'bell peppers', amount: 2, unit: 'whole' },
			{ name: 'onion', amount: 1, unit: 'whole' },
			{ name: 'garlic', amount: 2, unit: 'cloves' },
			{ name: 'olive oil', amount: 2, unit: 'tbsp' },
		],
		instructions: [
			'Cook brown rice according to package instructions',
			'Season chicken breast with garlic and olive oil',
			'Grill or pan-fry chicken until cooked through',
			'Sauté peppers and onions until tender',
			'Slice chicken and serve over rice with vegetables',
		],
		prepTime: 15,
		cookTime: 25,
		servings: 1,
		nutritionalInfo: {
			calories: 500,
			protein: 35,
			carbs: 40,
			fat: 18,
		},
		tags: ['dinner'],
		dietaryPreferences: ['high-protein'],
		restrictions: [],
	},
	{
		id: 'default-dinner-4',
		userId: 'default-user',
		name: 'Mediterranean Pasta',
		description: 'Light and flavorful Mediterranean pasta dish',
		ingredients: [
			{ name: 'whole wheat pasta', amount: 2, unit: 'cups' },
			{ name: 'cherry tomatoes', amount: 2, unit: 'cups' },
			{ name: 'spinach', amount: 2, unit: 'cups' },
			{ name: 'feta cheese', amount: 0.5, unit: 'cup' },
			{ name: 'olive oil', amount: 2, unit: 'tbsp' },
			{ name: 'basil', amount: 0.25, unit: 'cup' },
		],
		instructions: [
			'Cook pasta according to package instructions',
			'Heat olive oil in a large pan',
			'Add tomatoes and cook until softened',
			'Add spinach and cook until wilted',
			'Combine with pasta',
			'Top with feta cheese and fresh basil',
		],
		prepTime: 10,
		cookTime: 20,
		servings: 1,
		nutritionalInfo: {
			calories: 450,
			protein: 15,
			carbs: 60,
			fat: 18,
		},
		tags: ['dinner'],
		dietaryPreferences: ['vegetarian'],
		restrictions: [],
	},
	{
		id: 'default-dinner-5',
		userId: 'default-user',
		name: 'Quinoa Buddha Bowl',
		description: 'Nutritious and colorful quinoa bowl',
		ingredients: [
			{ name: 'quinoa', amount: 1, unit: 'cup' },
			{ name: 'chickpeas', amount: 1, unit: 'can' },
			{ name: 'kale', amount: 2, unit: 'cups' },
			{ name: 'avocado', amount: 1, unit: 'whole' },
			{ name: 'tahini', amount: 2, unit: 'tbsp' },
			{ name: 'lemon', amount: 1, unit: 'whole' },
		],
		instructions: [
			'Cook quinoa according to package instructions',
			'Massage kale with olive oil and salt',
			'Roast chickpeas with spices',
			'Slice avocado',
			'Combine all ingredients in a bowl',
			'Drizzle with tahini and lemon juice',
		],
		prepTime: 15,
		cookTime: 20,
		servings: 1,
		nutritionalInfo: {
			calories: 480,
			protein: 18,
			carbs: 55,
			fat: 22,
		},
		tags: ['dinner'],
		dietaryPreferences: ['vegetarian', 'vegan'],
		restrictions: [],
	},
];
