version: '3.8'

services:
  ai-service:
    build: .
    container_name: mealprep360-ai-service
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - mealprep360

  redis:
    image: redis:7-alpine
    container_name: mealprep360-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mealprep360

volumes:
  redis_data:

networks:
  mealprep360:
    driver: bridge

