services:
  ai-service:
    build: .
    container_name: mealprep360-ai-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    network_mode: bridge

