version: '3.8'

services:
  # Main API and Workers
  mealprep360-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TOKEN=${REDIS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_GPT_ID=${OPENAI_GPT_ID}
      - API_KEY=${API_KEY}
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
      - RATE_LIMIT_DELAY_MS=8000
      - MAX_RECIPE_FAILURES=15
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "require('http').get('http://localhost:3000/api/health', (res) => process.exit(res.statusCode === 200 ? 0 : 1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Dedicated Workers (optional - for scaling)
  mealprep360-workers:
    build: .
    command: ['node', 'dist/workers/startAll.js']
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_USER=${REDIS_USER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_URL=${REDIS_URL}
      - REDIS_TOKEN=${REDIS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_GPT_ID=${OPENAI_GPT_ID}
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
      - RATE_LIMIT_DELAY_MS=8000
      - MAX_RECIPE_FAILURES=15
      - IS_WORKER=true
    restart: unless-stopped
    depends_on:
      - mealprep360-api

  # Local Redis (for development only)
  redis-local:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    profiles:
      - local

  # Local MongoDB (for development only)
  mongodb-local:
    image: mongo:7
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mealprep360
    volumes:
      - mongodb_data:/data/db
    profiles:
      - local

volumes:
  redis_data:
  mongodb_data:
