export const TAGS_TO_REMOVE = [
	'freezer-friendly',
	'freezer',
	'meal prep',
	'meal-preparation',
	'freezer meal',
	'freezer-friendly meal',
	'freezer prep',
	'freezer-ready',
	'freezer-safe',
	'freezer meal prep',
	'freezer-friendly prep',
	'freezer-ready meal',
	'freezer-safe meal',
	'freezer meal preparation',
	'freezer-friendly preparation',
	'freezer-ready preparation',
	'freezer-safe preparation',
	'make-ahead',
	'batch-prep',
	'batch prep',
	'batch-prepping',
	'batch prepping',
	'batch cooking',
	'batch-cooking',
	'meal-prepping',
	'meal prepping',
	'prep-ahead',
	'prep ahead',
	'make ahead',
];
