export const FREEZER_TITLE_PATTERNS = [
	'Freezer-Friendly',
	'Freezer-Prep',
	'Freezer-Ready',
	'Freezer-Safe',
	'Freezer',
	'Freezer Meal',
	'Freezer-Ready Meal',
	'Freezer-Friendly Meal',
	'Freezer-Prep Meal',
	'(Freezer Prep)',
	'(Freezer-Friendly)',
	'(Freezer-Ready)',
	'(Freezer-Safe)',
	'(Freezer)',
	'(Freezer Meal)',
	'(Freezer-Ready Meal)',
	'(Freezer-Friendly Meal)',
	'(Freezer-Prep Meal)',
	'Freezer Prep Edition',
	'Freezer-Friendly Edition',
	'Freezer-Ready Edition',
	'Freezer-Safe Edition',
	'Freezer Edition',
	'(Freezer Prep Edition)',
	'(Freezer-Friendly Edition)',
	'(Freezer-Ready Edition)',
	'(Freezer-Safe Edition)',
	'(Freezer Edition)',
] as const;
