apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-service
  template:
    metadata:
      labels:
        app: planning-service
    spec:
      containers:
        - name: planning
          image: ghcr.io/mealprep360/planning-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4010
          env:
            - name: PORT
              value: '4010'
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
