// Tags that should be excluded from filtering/display
export const EXCLUDED_TAGS = new Set([
	'recipe',
	'food',
	'cooking',
	'meal',
	'dish',
	'cuisine',
	'ingredient',
	'kitchen',
	'homemade',
	'fresh',
	'delicious',
	'tasty',
	'yummy',
	'easy',
	'simple',
	'quick',
	'fast',
	'basic',
	'traditional',
	'classic',
	'popular',
	'common',
	'regular',
	'normal',
	'standard',
	'everyday',
	'main',
	'side',
	'course',
	'preparation',
	'method',
	'technique',
	'style',
	'type',
	'category',
	'group',
	'family',
	'variety',
	'kind',
	'sort',
	'version',
	'option',
	'choice',
	'selection',
	'pick',
]);

// Mapping for tag standardization
export const TAG_MAPPINGS: { [key: string]: string } = {
	// Cuisine types
	italian: 'Italian',
	mexican: 'Mexican',
	asian: 'Asian',
	chinese: 'Chinese',
	japanese: 'Japanese',
	thai: 'Thai',
	indian: 'Indian',
	french: 'French',
	mediterranean: 'Mediterranean',
	american: 'American',
	greek: 'Greek',
	spanish: 'Spanish',
	korean: 'Korean',
	vietnamese: 'Vietnamese',
	'middle eastern': 'Middle Eastern',
	lebanese: 'Lebanese',
	moroccan: 'Moroccan',
	turkish: 'Turkish',
	german: 'German',
	british: 'British',
	russian: 'Russian',
	brazilian: 'Brazilian',
	caribbean: 'Caribbean',

	// Dietary restrictions
	vegetarian: 'Vegetarian',
	vegan: 'Vegan',
	'gluten-free': 'Gluten-Free',
	'gluten free': 'Gluten-Free',
	'dairy-free': 'Dairy-Free',
	'dairy free': 'Dairy-Free',
	'nut-free': 'Nut-Free',
	'nut free': 'Nut-Free',
	'low-carb': 'Low-Carb',
	'low carb': 'Low-Carb',
	keto: 'Keto',
	ketogenic: 'Keto',
	paleo: 'Paleo',
	whole30: 'Whole30',
	'low-fat': 'Low-Fat',
	'low fat': 'Low-Fat',
	'sugar-free': 'Sugar-Free',
	'sugar free': 'Sugar-Free',
	diabetic: 'Diabetic',
	'heart-healthy': 'Heart-Healthy',
	'heart healthy': 'Heart-Healthy',

	// Meal types
	breakfast: 'Breakfast',
	lunch: 'Lunch',
	dinner: 'Dinner',
	brunch: 'Brunch',
	snack: 'Snack',
	appetizer: 'Appetizer',
	dessert: 'Dessert',
	beverage: 'Beverage',
	drink: 'Beverage',
	cocktail: 'Cocktail',
	smoothie: 'Smoothie',
	soup: 'Soup',
	salad: 'Salad',
	sandwich: 'Sandwich',
	pizza: 'Pizza',
	pasta: 'Pasta',
	rice: 'Rice',
	noodles: 'Noodles',
	bread: 'Bread',
	cake: 'Cake',
	cookies: 'Cookies',
	muffins: 'Muffins',
	pie: 'Pie',

	// Cooking methods
	baked: 'Baked',
	grilled: 'Grilled',
	fried: 'Fried',
	roasted: 'Roasted',
	steamed: 'Steamed',
	boiled: 'Boiled',
	sautéed: 'Sautéed',
	sauteed: 'Sautéed',
	braised: 'Braised',
	'slow-cooked': 'Slow-Cooked',
	'slow cooked': 'Slow-Cooked',
	'pressure-cooked': 'Pressure-Cooked',
	'pressure cooked': 'Pressure-Cooked',
	'air-fried': 'Air-Fried',
	'air fried': 'Air-Fried',
	'no-cook': 'No-Cook',
	'no cook': 'No-Cook',
	raw: 'Raw',

	// Protein types
	chicken: 'Chicken',
	beef: 'Beef',
	pork: 'Pork',
	fish: 'Fish',
	seafood: 'Seafood',
	salmon: 'Salmon',
	tuna: 'Tuna',
	shrimp: 'Shrimp',
	turkey: 'Turkey',
	lamb: 'Lamb',
	duck: 'Duck',
	eggs: 'Eggs',
	tofu: 'Tofu',
	beans: 'Beans',
	lentils: 'Lentils',
	quinoa: 'Quinoa',

	// Occasions
	holiday: 'Holiday',
	christmas: 'Christmas',
	thanksgiving: 'Thanksgiving',
	easter: 'Easter',
	halloween: 'Halloween',
	birthday: 'Birthday',
	party: 'Party',
	bbq: 'BBQ',
	picnic: 'Picnic',
	potluck: 'Potluck',
	'date-night': 'Date Night',
	'date night': 'Date Night',
	family: 'Family',
	kids: 'Kids',
	romantic: 'Romantic',

	// Difficulty/Time
	easy: 'Easy',
	quick: 'Quick',
	'30-minute': '30-Minute',
	'30 minute': '30-Minute',
	'one-pot': 'One-Pot',
	'one pot': 'One-Pot',
	'make-ahead': 'Make-Ahead',
	'make ahead': 'Make-Ahead',
	'freezer-friendly': 'Freezer-Friendly',
	'freezer friendly': 'Freezer-Friendly',
	'meal-prep': 'Meal-Prep',
	'meal prep': 'Meal-Prep',

	// Seasons
	spring: 'Spring',
	summer: 'Summer',
	fall: 'Fall',
	autumn: 'Fall',
	winter: 'Winter',

	// Temperature
	hot: 'Hot',
	cold: 'Cold',
	warm: 'Warm',
	chilled: 'Chilled',
	frozen: 'Frozen',

	// Texture/Style
	creamy: 'Creamy',
	crunchy: 'Crunchy',
	crispy: 'Crispy',
	smooth: 'Smooth',
	chunky: 'Chunky',
	spicy: 'Spicy',
	mild: 'Mild',
	sweet: 'Sweet',
	savory: 'Savory',
	tangy: 'Tangy',
	rich: 'Rich',
	light: 'Light',
	heavy: 'Heavy',
	comfort: 'Comfort Food',
	'comfort food': 'Comfort Food',
	healthy: 'Healthy',
	indulgent: 'Indulgent',
};
