export enum NotificationType {
	MEAL_PLAN_CREATED = 'MEAL_PLAN_CREATED',
	MEAL_PLAN_UPDATED = 'MEAL_PLAN_UPDATED',
	SHOPPING_LIST_GENERATED = 'SHOPPING_LIST_GENERATED',
	RECIPE_ADDED = 'RECIPE_ADDED',
	RECIPE_UPDATED = 'RECIPE_UPDATED',
	SYSTEM_UPDATE = 'SYSTEM_UPDATE',
	GENERAL = 'GENERAL',
}
